voluntario1 = int(input("Digite o valor arrecadado"))
voluntario2 = int(input("Digite o valor arrecadado"))
voluntario3 = int(input("Digite o valor arrecadado"))
voluntario4 = int(input("Digite o valor arrecadado"))
voluntario5 = int(input("Digite o valor arrecadado"))
voluntario6 = int(input("Digite o valor arrecadado"))
voluntario7 = int(input("Digite o valor arrecadado"))
voluntario8 = int(input("Digite o valor arrecadado"))
voluntario9 = int(input("Digite o valor arrecadado"))
voluntario10 = int(input("Digite o valor arrecadado"))
total = voluntario1 + voluntario2 + voluntario3 + voluntario4 + voluntario5 + voluntario6 + voluntario7 +voluntario8 +voluntario9 + voluntario10
print("o valor arrecadado da campanha foi:",total)